OwnIdentity.clone(): Fix to clone mLastFetchedDate
Unlikely I usually do, I this time did NOT manually check all callers
for whether they use it for anything serious; which is usually necessary
to decide whether we need upgrade code for old databases to fix
breakage.
I didn't do that because I worked enough with the codebase to trust my
memory of how we use clone():
We typically use it for three things for all of which the lack of
copying the Date doesn't matter:
- event-notifications. In that case, it won't matter to not propagate
that Date because it isn't propagated by FCP either. Also
event-notifications are currently dropped at every restart.
- *Temporary* clones in e.g. the UI which aren't stored in the database
and thus it won't matter as the breakage won't persist.
- Unit tests, which don't persist anything either.

Or in other words: Clones are never stored in the database except for
event-notifications, and there it doesn't matter.

This fixes the unit test failure introduced by the previous commit:

Testsuite: plugins.WebOfTrust.OwnIdentityTest
Testcase: testClone took 9.398 sec
    FAILED
junit.framework.AssertionFailedError: protected java.util.Date plugins.WebOfTrust.Identity.mLastFetchedDate expected:<Sat Dec 03 03:49:46 CET 2016> but was:<Thu Jan 01 01:00:00 CET 1970>
    at plugins.WebOfTrust.AbstractJUnit3BaseTest.testClone(AbstractJUnit3BaseTest.java:124)
    at plugins.WebOfTrust.OwnIdentityTest.testClone(OwnIdentityTest.java:116)