FCPInterface: Fix bogus unchecked typecasting
- Also remove FIXME which demands to introduce more of it
- The symptom would be this unit test failure:
org.junit.ComparisonFailure: expected:<[Trust]s> but was:<[Identitie]s>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at plugins.WebOfTrust.SubscriptionManagerFCPTest
		.testSubscribeTo(SubscriptionManagerFCPTest.java:193)
	at plugins.WebOfTrust.SubscriptionManagerFCPTest
		.testSubscribeUnsubscribe(SubscriptionManagerFCPTest.java:147)
	at plugins.WebOfTrust.SubscriptionManagerFCPTest
		.testSubscribeUnsubscribe(SubscriptionManagerFCPTest.java:140)