IdentityFileDiskQueue: Fix missing directory creation
Would cause WOT startup to fail:
The plugin WebOfTrust.jar could not be loaded: class
java.lang.RuntimeException: Cannot create
WebOfTrust/IdentityFileQueue/Queued