Identity.clone(): Fix to clone mLastFetchedDate
For an explanation of why this doesn't require code to repair old
databases see 479f6766f9025cb13e43a685eb37a2ef5c2b91f1 which did the
same fix for OwnIdentity.clone().

Fixes the unit test failure introduced by the previous commit:

Testcase: testClone took 2.38 sec
    FAILED
junit.framework.AssertionFailedError: protected java.util.Date plugins.WebOfTrust.Identity.mLastFetchedDate expected:<Sun Dec 04 03:38:43 CET 2016> but was:<Thu Jan 01 01:00:00 CET 1970>
    at plugins.WebOfTrust.AbstractJUnit3BaseTest.testClone(AbstractJUnit3BaseTest.java:124)
    at plugins.WebOfTrust.IdentityTest.testClone(IdentityTest.java:95)