XMLTransformer.importIdentity(): Fix IllegalStateException
Trying to import an edition which was previously imported and
marked with a FetchState of ParsingFailed but for which parsing did
now succeed would result in:
> java.lang.IllegalStateException: onFetched() called for old edition!
>   Passed edition: 217; Last fetched edition: 217
> at plugins.WebOfTrust.Identity.onFetched(Identity.java:710)
> at plugins.WebOfTrust.Identity.onFetchedAndParsedSuccessfully(Identity.java:676)
> at plugins.WebOfTrust.XMLTransformer.importIdentity(XMLTransformer.java:518)

And the throwing is a correct implementation of Identity.onFetched()
IMHO: It rightfully detects that it was already called for that edition.

Losing the hereby removed branch of code is not an issue:

- The proper approach of implementing re-fetching of an edition for
  which parsing failed is setting the FetchState to "NotFetched"
  instead of keeping it at ParsingFailed so the database actually tells
  the IdentityDownloader to download it again.
  We can safely assume that this proper approach will be chosen in
  future code because it is likely to use Identity.markForRefetch(), and
  that function was changed by commit
  fb04bb371ad82ddfa786891936ee04b8922d7a48 to not keep a previous
  FetchState of ParsingFailed but change it to NotFetched instead.

- With regards to existing user databases where the FetchState might
  still be ParsingFailed for some Identitys which ought to be refetched:
  Commit 58de49821b69e9bdc0e8f6ea48214feb5b601a21 shipped database
  upgrade code to set the FetchState to NotFetched for all Identitys
  where it was ParsingFailed.

- The fact that the above stack trace happened for me likely was not
  because the code path is assumed to exist by some other code (I'm
  quite confident I never wrote any WoT code which does that).
  Instead, my test runs had been lacking the aforementioned fix for
  markForRefetch(). If Trust-changes - which can happen at any time and
  are unrelated to this code path - caused markForRefetch() to be called
  upon an Identity which was marked as ParsingFailed it would decrease
  the edition of the Identity but keep the FetchState at ParsingFailed.
  The previous edition might be parseable so if something downloaded it
  again we would run into this stack trace.
  And that could indeed happen due to:
  - the previous lack of code in IdentityDownloaderSlow to prevent it
    from downloading multiple editions of the same Identity in parallel.
    See: https://bugs.freenetproject.org/view.php?id=6940
  - the concurrent operation of IdentityDownloaderFast and *Slow
    meaning they could download multiple editions of the same Identity
    in parallel.