WoTTest.testRestoreOwnIdentity_Unfetched(): Move failure to other test
It is better to require deleteOwnIdentity() to act upon this than
restoreOwnIdentity() because it will be backwards compatible, i.e. users
with broken old databases can use deleteOwnIdentity() to fix them.

This reverts part of 0bf2e5c05ea681c9bfa851138d0c3ac6bdc2579f.
The storeAndCommit() must be kept due to unrelated changes in between.
Also, the comment which was removed is not added back because IMHO it
didn't make sense there, it was likely an accidental copypaste leftover.

testRestoreOwnIdentity_Unfetched() should now succeed, and therefore
testDeleteOwnIdentity_Unfetched() will fail instead:
> junit.framework.AssertionFailedError: expected:<0> but was:<5>
> 	at plugins.WebOfTrust.WoTTest.testDeleteOwnIdentity_Unfetched(WoTTest.java:1223)

The failure will be fixed by an upcoming commit.