OwnIdentity: Fix to cause OwnIdentityTest to fail due to bug
The test wouldn't fail prevously without the assert because
Logger.error() currently does not cause tests to fail.

It now should always fail.
Will fix the failure in an upcoming commit.

The failure looks like this:

testGetNextEditionToInsert(plugins.WebOfTrust.OwnIdentityTest) Random seed: -8170645466025693860
Testcase: testGetNextEditionToInsert took 1.708 sec
    Caused an ERROR
java.lang.AssertionError: java.lang.IllegalStateException: onFetched() called for old edition! Passed edition: 0; Last fetched edition: 0
    at plugins.WebOfTrust.OwnIdentity.onInserted(OwnIdentity.java:350)
    at plugins.WebOfTrust.OwnIdentityTest.testGetNextEditionToInsert(OwnIdentityTest.java:165)
Caused by: java.lang.IllegalStateException: onFetched() called for old edition! Passed edition: 0; Last fetched edition: 0
    at plugins.WebOfTrust.Identity.onFetched(Identity.java:742)
    at plugins.WebOfTrust.OwnIdentity.onFetched(OwnIdentity.java:194)
    at plugins.WebOfTrust.OwnIdentity.onInserted(OwnIdentity.java:348)