Score: Fix failure of ScoreTest
Luckily this cannot have caused any database integrity corruption which
we would have to fix:
The versionID is currently only being used by SubscriptionManager -
and it deletes all its database objects at every restart.

The failure was:

junit.framework.AssertionFailedError: expected:<eee743b0-72d4-4e79-b2ef-667d3fd19977> but was:<176a1fa5-beb6-4810-b9d7-afe5a80734bd>
    at plugins.WebOfTrust.ScoreTest.testStoreWithoutCommit(ScoreTest.java:570)