(Own)Identity.clone(): Fix failure of preserving mLastChangedDate
- Fixes the web interface's "My identities" page always saying that
every identity was changed at the same moment when the page was
displayed
- Fixes (Own)IdentityTest.testClone() failures similar to:

junit.framework.AssertionFailedError: protected java.util.Date
plugins.WebOfTrust.Identity.mLastChangedDate expected:<Tue Mar 10
05:48:36 CET 2015> but was:<Tue Mar 10 05:48:36 CET 2015>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at plugins.WebOfTrust.AbstractJUnit3BaseTest
		.testClone(AbstractJUnit3BaseTest.java:117)
	at plugins.WebOfTrust.OwnIdentityTest
		.testClone(OwnIdentityTest.java:98)