ScoreTest: Test storeWithoutCommit(), fail intentionally due to detecting a bug in Score
Fails with:
junit.framework.AssertionFailedError: expected:<d7125633-b3a7-4855-8a6c-1cb09f2a9938> but was:<4adb488f-49f1-4ad2-bf22-d06af572a148>
    at plugins.WebOfTrust.ScoreTest.testStoreWithoutCommit(ScoreTest.java:570)

This is because Score.clone() does not copy the mVersionID
member variable.
Will be fixed in upcoming commit.