WoTTest.testRestoreOwnIdentity_Unfetched(): Fix to detect bogus edition handling in restoreOwnIdentity(); fail intentionally
The removed comment was not only wrong with its intention, but also
about the edition - the URI requestUriO does in fact *not* contain a
higher edition, so we instead must manually make it higher.

Should now fail with:
> junit.framework.AssertionFailedError: expected:<5> but was:<9>
>	at plugins.WebOfTrust.WoTTest.testRestoreOwnIdentity_Unfetched(WoTTest.java:1153)

The failure will be fixed by an upcoming commit.