EditionHintTest: Fix not catching bug, should fail now
Should fail with seed 3119124416517353315L.
To ease seeing the reason for failure, comment out line 283 of
EditionHint (next commit will do that):
    assert(result == compareTo_ReferenceImplementation(o));

If that's commented out, it should fail with:

Testcase: testCompareTo took 6.317 sec
    FAILED
junit.framework.AssertionFailedError: expected:<-1> but was:<-2>
    at plugins.WebOfTrust.network.input.EditionHintTest.testCompareTo(EditionHintTest.java:118)