ScoreTest.testEquals(): Fix IllegalArgumentException
Was induced by Score.setCapacity() having been made more strict by
commit 579a133154d315c5544988b72b8a8a882d1945fc

java.lang.IllegalArgumentException: Illegal capacity: 3
    at plugins.WebOfTrust.Score.setCapacity(Score.java:321)
    at plugins.WebOfTrust.Score.<init>(Score.java:189)
    at plugins.WebOfTrust.ScoreTest.testEquals(ScoreTest.java:612)