ScoreID/TrustID.constructAndValidate(): Fix to detect too short IDs
Fixes the unit test failure introduced by the second to last failure:

----
Testcase: testScoreIDconstructAndValidateString took 1.856 sec
    FAILED
Must not be accepted: AbjDTosPDxzmdlgANbylbKB~WSJ77hMyM1rjAhYl0Y@S1Uq4ctRkoarKw3qEdRa7uJm1phPzexoxXdpp0V2iMI
junit.framework.AssertionFailedError: Must not be accepted: AbjDTosPDxzmdlgANbylbKB~WSJ77hMyM1rjAhYl0Y@S1Uq4ctRkoarKw3qEdRa7uJm1phPzexoxXdpp0V2iMI
    at plugins.WebOfTrust.ScoreTest.testScoreIDconstructAndValidateString(ScoreTest.java:106)
----

ScoreTest should succeed now.