Score: Fix test failure due to mLastChangeDate sometimes not matching mCreationDate
Fixes:

Testcase: testGetDateOfLastChange took 1.865 sec
    FAILED
junit.framework.AssertionFailedError: expected: java.util.Date<Sun Oct 09 03:50:09 CEST 2016>
  but was: java.util.Date<Sun Oct 09 03:50:09 CEST 2016>
    at plugins.WebOfTrust.ScoreTest.testGetDateOfLastChange(ScoreTest.java:658)